### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by nicholsn** [clinical-meteor/meteor-on-fhir#212]
I'm trying to build meteor-on-fhir on a mac, but I am getting the following error. Any thoughts on what I'm doing wrong here?

```
[[[[[ ~/Code/meteor-on-fhir/webapp ]]]]]

=> Started proxy.
=> A patch (Meteor 1.4.2.7) for your current release is available!
   Update this project now with 'meteor update --patch'.
=> Started MongoDB.
W20170326-15:42:00.109(-7)? (STDERR) /Users/nicholb3/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170326-15:42:00.139(-7)? (STDERR) 						throw(ex);
W20170326-15:42:00.140(-7)? (STDERR) 						^
W20170326-15:42:00.140(-7)? (STDERR)
W20170326-15:42:00.140(-7)? (STDERR) TypeError: Cannot read property 'fhir' of undefined
W20170326-15:42:00.140(-7)? (STDERR)     at meteorInstall.server.metadata.js (server/metadata.js:54:5)
W20170326-15:42:00.141(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:188:9)
W20170326-15:42:00.141(-7)? (STDERR)     at require (packages/modules-runtime.js:111:16)
W20170326-15:42:00.141(-7)? (STDERR)     at /Users/nicholb3/Code/meteor-on-fhir/webapp/.meteor/local/build/programs/server/app/app.js:4117:1
W20170326-15:42:00.142(-7)? (STDERR)     at /Users/nicholb3/Code/meteor-on-fhir/webapp/.meteor/local/build/programs/server/boot.js:295:34
W20170326-15:42:00.142(-7)? (STDERR)     at Array.forEach (native)
W20170326-15:42:00.142(-7)? (STDERR)     at Function._.each._.forEach (/Users/nicholb3/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170326-15:42:00.142(-7)? (STDERR)     at /Users/nicholb3/Code/meteor-on-fhir/webapp/.meteor/local/build/programs/server/boot.js:128:5
W20170326-15:42:00.142(-7)? (STDERR)     at /Users/nicholb3/Code/meteor-on-fhir/webapp/.meteor/local/build/programs/server/boot.js:344:5
W20170326-15:42:00.142(-7)? (STDERR)     at Function.run (/Users/nicholb3/Code/meteor-on-fhir/webapp/.meteor/local/build/programs/server/profile.js:480:12)
=> Exited with code: 1
W20170326-15:42:04.069(-7)? (STDERR) /Users/nicholb3/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170326-15:42:04.069(-7)? (STDERR) 						throw(ex);
W20170326-15:42:04.069(-7)? (STDERR) 						^
W20170326-15:42:04.070(-7)? (STDERR)
W20170326-15:42:04.070(-7)? (STDERR) TypeError: Cannot read property 'fhir' of undefined
W20170326-15:42:04.070(-7)? (STDERR)     at meteorInstall.server.metadata.js (server/metadata.js:54:5)
W20170326-15:42:04.070(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:188:9)
W20170326-15:42:04.070(-7)? (STDERR)     at require (packages/modules-runtime.js:111:16)
W20170326-15:42:04.070(-7)? (STDERR)     at /Users/nicholb3/Code/meteor-on-fhir/webapp/.meteor/local/build/programs/server/app/app.js:4117:1
W20170326-15:42:04.070(-7)? (STDERR)     at /Users/nicholb3/Code/meteor-on-fhir/webapp/.meteor/local/build/programs/server/boot.js:295:34
W20170326-15:42:04.071(-7)? (STDERR)     at Array.forEach (native)
W20170326-15:42:04.071(-7)? (STDERR)     at Function._.each._.forEach (/Users/nicholb3/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170326-15:42:04.071(-7)? (STDERR)     at /Users/nicholb3/Code/meteor-on-fhir/webapp/.meteor/local/build/programs/server/boot.js:128:5
W20170326-15:42:04.071(-7)? (STDERR)     at /Users/nicholb3/Code/meteor-on-fhir/webapp/.meteor/local/build/programs/server/boot.js:344:5
W20170326-15:42:04.071(-7)? (STDERR)     at Function.run (/Users/nicholb3/Code/meteor-on-fhir/webapp/.meteor/local/build/programs/server/profile.js:480:12)
=> Exited with code: 1
W20170326-15:42:07.614(-7)? (STDERR) /Users/nicholb3/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170326-15:42:07.614(-7)? (STDERR) 						throw(ex);
W20170326-15:42:07.614(-7)? (STDERR) 						^
W20170326-15:42:07.615(-7)? (STDERR)
W20170326-15:42:07.615(-7)? (STDERR) TypeError: Cannot read property 'fhir' of undefined
W20170326-15:42:07.615(-7)? (STDERR)     at meteorInstall.server.metadata.js (server/metadata.js:54:5)
W20170326-15:42:07.615(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:188:9)
W20170326-15:42:07.616(-7)? (STDERR)     at require (packages/modules-runtime.js:111:16)
W20170326-15:42:07.616(-7)? (STDERR)     at /Users/nicholb3/Code/meteor-on-fhir/webapp/.meteor/local/build/programs/server/app/app.js:4117:1
W20170326-15:42:07.616(-7)? (STDERR)     at /Users/nicholb3/Code/meteor-on-fhir/webapp/.meteor/local/build/programs/server/boot.js:295:34
W20170326-15:42:07.616(-7)? (STDERR)     at Array.forEach (native)
W20170326-15:42:07.616(-7)? (STDERR)     at Function._.each._.forEach (/Users/nicholb3/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170326-15:42:07.616(-7)? (STDERR)     at /Users/nicholb3/Code/meteor-on-fhir/webapp/.meteor/local/build/programs/server/boot.js:128:5
W20170326-15:42:07.616(-7)? (STDERR)     at /Users/nicholb3/Code/meteor-on-fhir/webapp/.meteor/local/build/programs/server/boot.js:344:5
W20170326-15:42:07.616(-7)? (STDERR)     at Function.run (/Users/nicholb3/Code/meteor-on-fhir/webapp/.meteor/local/build/programs/server/profile.js:480:12)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

**Comment by awatson1978** [comment]
Hi @nicholsn,
You're not using a `settings.json` file.  You need to use a ``meteor --settings settings.json` and one of the config files.

**Comment by nicholsn** [comment]
Cool, thanks! Its now working - looking forward to checking this out.
