### ISSUE TITLE
First time clone and start: initializeUsers check got undefined

### ISSUE THREAD

**Issue by ihealthdavid** [clinical-meteor/meteor-on-fhir#237]
Steps to replicate:
```
git clone https://github.com/clinical-meteor/meteor-on-fhir
NODE_ENV=test INITIALIZE=true Patients=true Practitioners=true meteor --settings settings.dev.json
```

Output:
```
I20170808-16:16:35.590(-7)? INITIALZING
I20170808-16:16:35.591(-7)? No RiskAssessments found.  Creating some...
I20170808-16:16:35.592(-7)? Initializing HouseMD users...
W20170808-16:16:35.595(-7)? (STDERR)
W20170808-16:16:35.595(-7)? (STDERR) /Users/davidson1/.meteor/packages/meteor-tool/.1.4.2_3.7n7h1r++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170808-16:16:35.596(-7)? (STDERR)                                            throw(ex);
W20170808-16:16:35.596(-7)? (STDERR)                                            ^
W20170808-16:16:35.894(-7)? (STDERR) Error: Match error: Expected object, got undefined
W20170808-16:16:35.894(-7)? (STDERR)     at exports.check (packages/check.js:57:15)
W20170808-16:16:35.895(-7)? (STDERR)     at [object Object].Meteor.methods.initializeUsers (packages/clinical_accounts-housemd.js:63:5)
W20170808-16:16:35.895(-7)? (STDERR)     at packages/check.js:130:16
W20170808-16:16:35.895(-7)? (STDERR)     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
W20170808-16:16:35.896(-7)? (STDERR)     at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
W20170808-16:16:35.896(-7)? (STDERR)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1708:18)
W20170808-16:16:35.896(-7)? (STDERR)     at packages/ddp-server/livedata_server.js:1624:18
W20170808-16:16:35.896(-7)? (STDERR)     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
W20170808-16:16:35.897(-7)? (STDERR)     at Server.apply (packages/ddp-server/livedata_server.js:1623:45)
W20170808-16:16:35.897(-7)? (STDERR)     at Server.call (packages/ddp-server/livedata_server.js:1566:17)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
^C

```

On MacBook, OS X 10.11.6

**Comment by ihealthdavid** [comment]
Simply running without INITIALIZE works:
meteor --settings settings.dev.json

**Comment by awatson1978** [comment]
Hi!
Try `meteor update clinical:accounts-housemd`.  We updated the package last month to fix that, but the dependency is still in a feature branch and needs to be merged into `development`.

**Comment by ihealthdavid** [comment]
Thanks! That fixes it.
